//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THLSC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExeName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExeName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("THLSC.ExeName", typeof(ExeName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 東方紅魔郷.
        /// </summary>
        internal static string th06 {
            get {
                return ResourceManager.GetString("th06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th07.
        /// </summary>
        internal static string th07 {
            get {
                return ResourceManager.GetString("th07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th08.
        /// </summary>
        internal static string th08 {
            get {
                return ResourceManager.GetString("th08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th09.
        /// </summary>
        internal static string th09 {
            get {
                return ResourceManager.GetString("th09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th10.
        /// </summary>
        internal static string th10 {
            get {
                return ResourceManager.GetString("th10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th11.
        /// </summary>
        internal static string th11 {
            get {
                return ResourceManager.GetString("th11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th12.
        /// </summary>
        internal static string th12 {
            get {
                return ResourceManager.GetString("th12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th128.
        /// </summary>
        internal static string th128 {
            get {
                return ResourceManager.GetString("th128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th13.
        /// </summary>
        internal static string th13 {
            get {
                return ResourceManager.GetString("th13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th14.
        /// </summary>
        internal static string th14 {
            get {
                return ResourceManager.GetString("th14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th15.
        /// </summary>
        internal static string th15 {
            get {
                return ResourceManager.GetString("th15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th16.
        /// </summary>
        internal static string th16 {
            get {
                return ResourceManager.GetString("th16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th17.
        /// </summary>
        internal static string th17 {
            get {
                return ResourceManager.GetString("th17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th18.
        /// </summary>
        internal static string th18 {
            get {
                return ResourceManager.GetString("th18", resourceCulture);
            }
        }
    }
}
